Add travis ci configurations for coding standard check.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,43 +1,42 @@
-language: php
-dist: trusty
 sudo: false
+language: php
 
 php:
-  - 5.6
-  - 7.0
   - 7.1
 
-env:
-  global:
-    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
-    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
-  matrix:
-    - RELEASE=stable COMPOSER_CHANNEL=stable
-    - RELEASE=dev COMPOSER_CHANNEL=stable
-    - RELEASE=stable COMPOSER_CHANNEL=snapshot
-
 before_install:
-  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
+  - composer selfupdate
   - phpenv config-rm xdebug.ini
-  - composer --verbose self-update --$COMPOSER_CHANNEL
-  - composer --version
 
 install:
-  - composer --verbose install
+  - composer validate --no-check-all --ansi
+  - composer install
+  # Prepare a list of files that should be checked for coding standard.
+  # If the branch was force updated the commit range might not be good.
+  # In this case we get the difference between the master and this.
+  - git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
+  - |
+    if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
+      git remote add upstream https://github.com/drupaltransylvania/drupal-community-cluj
+      git remote set-branches --add upstream "$TRAVIS_BRANCH";
+      git fetch upstream;
+      TRAVIS_COMMIT_RANGE=upstream/"$TRAVIS_BRANCH"...;
+    fi
+  - git diff --name-only $TRAVIS_COMMIT_RANGE > changed_files.txt
+  - echo -e "\033[0;34m-- All detected changes:\033[0m" && cat changed_files.txt || true
+  # Filter out only the types of files we need to check.
+  - sed -i '/inc$\|info$\|install$\|module$\|php$\|profile$\|test$\|theme$/!d' changed_files.txt
+  - echo -e "\033[0;34m-- Changed files after extension filetering:\033[0m" && cat changed_files.txt || true
+  # Filter out deleted files which make code-sniffer fail.
+  # Also make sure the file is not empty before filtering because,
+  # in that case we will get a dot (.) in the file which will make
+  # php-cs scan everything.
+  - |
+    if [ -s changed_files.txt ] ; then
+      cat changed_files.txt | xargs ls -d 2>/dev/null > changed_existing_files.txt || true;
+    fi
+  - echo -e "\033[0;34m-- Files that will be sniffed:\033[0m" && cat changed_existing_files.txt || true
 
 script:
-  - if [[ $RELEASE = dev ]]; then composer --verbose remove --no-update drupal/console; fi;
-  # Remove symfony/routing once https://www.drupal.org/node/2882456 is fixed
-  # @see https://www.drupal.org/node/2887000
-  # @see https://www.drupal.org/node/2874909
-  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update symfony/event-dispatcher:~3.2.9 symfony/routing:~3.2.9 drupal/core:8.4.x-dev drush/drush:9.0.x-dev; fi;
-  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
-  - cd $TRAVIS_BUILD_DIR/web
-  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
-  - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
-  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
-  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
-  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
-  - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache
-  - ./../vendor/bin/drush
-  - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
+  # Run for each changed file the code sniffer.
+  - if [ "$TRAVIS_PULL_REQUEST" == "true" ] && [ -s changed_existing_files.txt ] && [ "$TRAVIS_BRANCH" != "master"] && [ "$TRAVIS_BRANCH" != "develop"] ; then ./vendor/bin/phpcs --file-list=changed_existing_files.txt; fi;
